"""added profile pic

Revision ID: 0c20d1b7a329
Revises: 6cf5b3d6e57c
Create Date: 2022-04-26 06:33:30.472608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c20d1b7a329'
down_revision = '6cf5b3d6e57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
